import { defineCompanyModel } from './company.model.js';
import { defineUserModel } from './user.model.js';
import { defineCompanyProfileModel } from './companyProfile.model.js';
import { defineSourceModel } from './source.model.js';
import { defineDataImportModel } from './dataImport.model.js';
import { defineProcessingRunModel } from './processingRun.model.js';
import { defineProcessedRecordModel } from './processedRecord.model.js';
import { defineExternalQueryModel } from './externalQuery.model.js';
import { defineAlertModel } from './alert.model.js';
import { defineBackupModel } from './backup.model.js';
import { defineRestoreEventModel } from './restoreEvent.model.js';
import { defineExportRecordModel } from './exportRecord.model.js';

export const initializeModels = (sequelize) => {
  const CompanyModel = defineCompanyModel(sequelize);
  const UserModel = defineUserModel(sequelize);
  const CompanyProfileModel = defineCompanyProfileModel(sequelize);
  const SourceModel = defineSourceModel(sequelize);
  const DataImportModel = defineDataImportModel(sequelize);
  const ProcessingRunModel = defineProcessingRunModel(sequelize);
  const ProcessedRecordModel = defineProcessedRecordModel(sequelize);
  const ExternalQueryModel = defineExternalQueryModel(sequelize);
  const AlertModel = defineAlertModel(sequelize);
  const BackupModel = defineBackupModel(sequelize);
  const RestoreEventModel = defineRestoreEventModel(sequelize);
  const ExportRecordModel = defineExportRecordModel(sequelize);
  const relation = {
    foreignKey: { name: 'companyId', allowNull: false },
    onDelete: 'RESTRICT', onUpdate: 'CASCADE',
  };
  CompanyModel.hasMany(UserModel, { ...relation, as: 'users' });
  UserModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasOne(CompanyProfileModel, { ...relation, as: 'profile' });
  CompanyProfileModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(SourceModel, { ...relation, as: 'sources' });
  SourceModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(DataImportModel, { ...relation, as: 'dataImports' });
  DataImportModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  SourceModel.hasMany(DataImportModel, { foreignKey: { name: 'sourceId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'dataImports' });
  DataImportModel.belongsTo(SourceModel, { foreignKey: { name: 'sourceId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'source' });
  CompanyModel.hasMany(ProcessingRunModel, { ...relation, as: 'processingRuns' });
  ProcessingRunModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  DataImportModel.hasMany(ProcessingRunModel, { foreignKey: { name: 'dataImportId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'processingRuns' });
  ProcessingRunModel.belongsTo(DataImportModel, { foreignKey: { name: 'dataImportId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'dataImport' });
  CompanyModel.hasMany(ProcessedRecordModel, { ...relation, as: 'processedRecords' });
  CompanyModel.hasMany(ExternalQueryModel, { ...relation, as: 'externalQueries' });
  ExternalQueryModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(AlertModel, { ...relation, as: 'alerts' });
  AlertModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(BackupModel, { ...relation, as: 'backups' });
  BackupModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(RestoreEventModel, { ...relation, as: 'restoreEvents' });
  RestoreEventModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  CompanyModel.hasMany(ExportRecordModel, { ...relation, as: 'exports' });
  ExportRecordModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  BackupModel.hasMany(RestoreEventModel, { foreignKey: { name: 'backupId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'restorations' });
  RestoreEventModel.belongsTo(BackupModel, { foreignKey: { name: 'backupId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'backup' });
  BackupModel.hasMany(RestoreEventModel, { foreignKey: { name: 'safetyBackupId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'safetyRestorations' });
  RestoreEventModel.belongsTo(BackupModel, { foreignKey: { name: 'safetyBackupId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'safetyBackup' });
  UserModel.hasMany(AlertModel, { foreignKey: { name: 'userId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'alerts' });
  AlertModel.belongsTo(UserModel, { foreignKey: { name: 'userId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'user' });
  UserModel.hasMany(ExternalQueryModel, { foreignKey: { name: 'userId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'externalQueries' });
  ExternalQueryModel.belongsTo(UserModel, { foreignKey: { name: 'userId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'user' });
  ProcessedRecordModel.belongsTo(CompanyModel, { ...relation, as: 'company' });
  SourceModel.hasMany(ProcessedRecordModel, { foreignKey: { name: 'sourceId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'processedRecords' });
  ProcessedRecordModel.belongsTo(SourceModel, { foreignKey: { name: 'sourceId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'source' });
  DataImportModel.hasMany(ProcessedRecordModel, { foreignKey: { name: 'dataImportId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'processedRecords' });
  ProcessedRecordModel.belongsTo(DataImportModel, { foreignKey: { name: 'dataImportId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'dataImport' });
  ProcessingRunModel.hasMany(ProcessedRecordModel, { foreignKey: { name: 'processingRunId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'processedRecords' });
  ProcessedRecordModel.belongsTo(ProcessingRunModel, { foreignKey: { name: 'processingRunId', allowNull: false }, onDelete: 'RESTRICT', onUpdate: 'CASCADE', as: 'processingRun' });
  return { CompanyModel, UserModel, CompanyProfileModel, SourceModel, DataImportModel, ProcessingRunModel, ProcessedRecordModel, ExternalQueryModel, AlertModel, BackupModel, RestoreEventModel, ExportRecordModel };
};
