'use client'

import { useState } from 'react'
import { AlertCircle, CheckCircle2, ChevronDown, CircleHelp, Cloud, Database, Download, LockKeyhole, MoreHorizontal, RefreshCw, ShieldCheck, UserRound, XCircle } from 'lucide-react'

function Logo() {
  return <div className="flex items-center gap-2.5"><div className="grid size-8 place-items-center rounded-lg bg-[#f4511e] shadow-[0_0_18px_rgba(244,81,30,.28)]"><span className="text-lg text-white">✣</span></div><span className="text-[15px] font-bold tracking-tight text-[#f3f5f7]">Stockflow</span></div>
}

function StatusPill({ children, tone = 'green' }) {
  const styles = { green: 'border-[#24563c] bg-[#102b20] text-[#62d89b]', blue: 'border-[#284b62] bg-[#102b3a] text-[#55b9ee]', amber: 'border-[#5a4c25] bg-[#382f17] text-[#f2c45c]', red: 'border-[#59303b] bg-[#3a1d26] text-[#ff8d94]' }
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-medium ${styles[tone]}`}><span className="size-1.5 rounded-full bg-current" />{children}</span>
}

function Metric({ label, value, detail, icon: Icon, color }) {
  return <article className="rounded-xl border border-[#293749] bg-[#0f1621] p-4"><div className="flex items-center justify-between"><span className="text-xs text-[#8a98aa]">{label}</span><span className="grid size-8 place-items-center rounded-lg" style={{ color, backgroundColor: `${color}18` }}><Icon size={16} /></span></div><p className="mt-4 text-xl font-semibold tracking-tight text-[#f3f5f7]">{value}</p><p className="mt-1 text-[11px] text-[#68778b]">{detail}</p></article>
}

export default function Page() {
  const [authorized, setAuthorized] = useState(true)
  const [operation, setOperation] = useState('idle')
  const [message, setMessage] = useState(null)

  function runBackup() {
    if (!authorized) return
    setOperation('running')
    setMessage(null)
    window.setTimeout(() => {
      setOperation('success')
      setMessage({ tone: 'success', title: 'Copia completada correctamente', body: 'La información se respaldó sin errores. Todos los registros están disponibles para restauración.' })
    }, 1100)
  }

  function downloadBackup() {
    if (!authorized) return
    setMessage({ tone: 'success', title: 'Descarga preparada', body: 'El archivo de respaldo está listo y comenzará a descargarse de forma segura.' })
  }

  return <main className="min-h-screen bg-[#090d15] text-[#f3f5f7]"><header className="border-b border-[#202b39] bg-[#0a0f18]/95"><div className="mx-auto flex h-[66px] max-w-[1180px] items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm text-[#8792a4] md:flex"><a className="hover:text-white" href="#alertas">Alertas</a><a className="text-[#e8edf3]" href="#respaldo">Respaldo</a><a className="hover:text-white" href="#fuentes">Fuentes</a></nav><div className="flex items-center gap-4"><span className="hidden text-sm text-[#8f9bac] sm:block">Hola, Martina</span><button aria-label="Abrir ayuda" className="grid size-8 place-items-center rounded-full border border-[#293546] text-[#8490a3]"><CircleHelp size={16} /></button><div className="grid size-8 place-items-center rounded-full bg-[#293546] text-xs font-semibold text-[#dbe2ea]">ML</div></div></div></header><div className="mx-auto max-w-[1180px] px-5 py-8 lg:px-8 lg:py-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-medium uppercase tracking-[.18em] text-[#ff792c]">Continuidad operativa</p><h1 className="text-2xl font-bold tracking-tight sm:text-[30px]">Respaldo de datos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8e9aac]">Consulta el estado de la última copia y ejecuta una operación segura cuando sea necesario.</p></div><div className="flex items-center gap-2 rounded-lg border border-[#293749] bg-[#0f1621] px-3 py-2"><UserRound size={15} className="text-[#8b98aa]" /><span className="text-xs text-[#a9b4c1]">Rol: Administradora</span><ChevronDown size={14} className="text-[#718096]" /></div></div>

<section id="respaldo" className="grid gap-4 md:grid-cols-3"><Metric label="Última copia" value="Hoy, 04:12" detail="25 de junio de 2025" icon={CheckCircle2} color="#62d89b" /><Metric label="Estado de operación" value="Completada" detail="Sin errores detectados" icon={ShieldCheck} color="#55b9ee" /><Metric label="Datos respaldados" value="2,84 GB" detail="18.420 registros incluidos" icon={Database} color="#a998ff" /></section>

<div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-lg bg-[#102b20] text-[#62d89b]"><Cloud size={18} /></span><div><h2 className="text-base font-semibold text-[#edf2f7]">Estado del respaldo</h2><p className="mt-0.5 text-xs text-[#758397]">Copia automática y manual de la información crítica</p></div></div></div><StatusPill tone={operation === 'running' ? 'blue' : operation === 'success' ? 'green' : 'green'}>{operation === 'running' ? 'En progreso' : 'Operación estable'}</StatusPill></div><div className="mt-6 rounded-lg border border-[#24563c] bg-[#102b20]/55 p-4"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-[#62d89b]" size={18} /><div><p className="text-sm font-semibold text-[#d9f7e7]">Última copia completada correctamente</p><p className="mt-1 text-xs leading-5 text-[#9ec8b1]">Todos los datos fueron verificados y están listos para restauración.</p></div></div><div className="mt-4 grid gap-3 border-t border-[#24563c]/70 pt-4 sm:grid-cols-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-[#6f9d83]">Fecha y hora</p><p className="mt-1 text-xs text-[#d4e8dc]">25 jun 2025 · 04:12</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#6f9d83]">Duración</p><p className="mt-1 text-xs text-[#d4e8dc]">06 min 42 s</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#6f9d83]">Destino</p><p className="mt-1 text-xs text-[#d4e8dc]">Almacenamiento seguro</p></div></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="max-w-md text-xs leading-5 text-[#77869a]">La copia automática se ejecuta todos los días a las 04:00. Una copia manual no reemplaza la programación automática.</p><button onClick={downloadBackup} disabled={!authorized} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#334154] bg-[#111d2a] px-4 text-sm font-medium text-[#d7e0e9] transition hover:border-[#52657c] hover:bg-[#182638] disabled:cursor-not-allowed disabled:opacity-40"><Download size={15} />Descargar última copia</button></div></section>

<aside className="rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-[#edf2f7]">Acciones</h2><p className="mt-1 text-xs leading-5 text-[#758397]">Gestiona las operaciones de respaldo disponibles.</p></div><MoreHorizontal size={18} className="text-[#718096]" /></div><div className="mt-5 rounded-lg border border-[#334154] bg-[#111d2a] p-3"><div className="flex items-start gap-2.5"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-[#f2c45c]" /><div><p className="text-xs font-medium text-[#e7edf3]">Acceso autorizado</p><p className="mt-1 text-[11px] leading-5 text-[#8290a3]">Solo administradores pueden iniciar o descargar respaldos.</p></div></div><button onClick={() => setAuthorized((value) => !value)} className="mt-3 text-[11px] font-medium text-[#55b9ee] hover:text-[#8dd5ff]">{authorized ? 'Simular usuario sin permisos' : 'Restaurar permisos de administradora'}</button></div><button onClick={runBackup} disabled={!authorized || operation === 'running'} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#f4511e] text-sm font-semibold text-white shadow-[0_8px_24px_rgba(244,81,30,.16)] transition hover:bg-[#ff6129] disabled:cursor-not-allowed disabled:bg-[#3a4451] disabled:text-[#8b98a8] disabled:shadow-none">{operation === 'running' ? <><RefreshCw className="animate-spin" size={16} />Generando respaldo...</> : <><Database size={16} />Crear copia ahora</>}</button>{!authorized && <p className="mt-3 flex items-start gap-2 text-[11px] leading-5 text-[#ff8d94]"><AlertCircle size={14} className="mt-0.5 shrink-0" />No tienes permisos suficientes para ejecutar esta acción.</p>}</aside></div>

{message && <div role="status" className={`mt-6 flex items-start gap-3 rounded-xl border p-4 ${message.tone === 'success' ? 'border-[#24563c] bg-[#102b20]/70' : 'border-[#59303b] bg-[#3a1d26]/70'}`}>{message.tone === 'success' ? <CheckCircle2 className="mt-0.5 shrink-0 text-[#62d89b]" size={18} /> : <XCircle className="mt-0.5 shrink-0 text-[#ff8d94]" size={18} />}<div><p className="text-sm font-semibold text-[#edf2f7]">{message.title}</p><p className="mt-1 text-xs text-[#9eabba]">{message.body}</p></div></div>}

<section className="mt-6 rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-[#edf2f7]">Historial de operaciones</h2><p className="mt-1 text-xs text-[#758397]">Registro de las últimas copias generadas por el sistema.</p></div><button className="text-xs font-medium text-[#55b9ee] hover:text-[#8dd5ff]">Ver historial completo</button></div><div className="mt-5 divide-y divide-[#202c3b]"><div className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#102b20] text-[#62d89b]"><CheckCircle2 size={15} /></span><div><p className="text-sm text-[#dce3eb]">Copia automática</p><p className="mt-0.5 text-[11px] text-[#718096]">25 jun 2025 · 04:12 · 2,84 GB</p></div></div><StatusPill>Completada</StatusPill></div><div className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#102b3a] text-[#55b9ee]"><Database size={15} /></span><div><p className="text-sm text-[#dce3eb]">Copia manual</p><p className="mt-0.5 text-[11px] text-[#718096]">24 jun 2025 · 15:38 · 2,81 GB</p></div></div><StatusPill tone="blue">Completada</StatusPill></div><div className="flex flex-wrap items-center justify-between gap-3 py-3 last:pb-0"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#3a1d26] text-[#ff8d94]"><XCircle size={15} /></span><div><p className="text-sm text-[#dce3eb]">Copia automática</p><p className="mt-0.5 text-[11px] text-[#718096]">23 jun 2025 · 04:00 · Interrumpida</p></div></div><StatusPill tone="red">Con error</StatusPill></div></div></section></div></main>
}
