import {
  AlertTriangle,
  Factory,
  History,
  Package,
  ShoppingCart,
  Sparkles,
  TrendingUp,
  Users,
} from "lucide-react"

export const dashboardWidgets = [
  {
    id: "sales",
    title: "Ventas",
    description: "Rendimiento del período",
    value: "$ 8.420.500",
    detail: "+12,8% vs. mes anterior",
    status: "ready",
    icon: TrendingUp,
    tone: "blue",
    bars: [38, 52, 44, 68, 58, 82, 74],
  },
  {
    id: "purchases",
    title: "Compras",
    description: "Inversión en proveedores",
    value: "$ 2.180.300",
    detail: "18 órdenes activas",
    status: "loading",
    icon: ShoppingCart,
    tone: "orange",
  },
  {
    id: "stock",
    title: "Stock",
    description: "Inventario disponible",
    value: "Sin datos",
    detail: "Conectá una fuente para comenzar",
    status: "empty",
    icon: Package,
    tone: "violet",
  },
  {
    id: "customers",
    title: "Clientes",
    description: "Actividad de clientes",
    value: "No disponible",
    detail: "No pudimos actualizar este widget",
    status: "error",
    icon: Users,
    tone: "rose",
  },
  {
    id: "production",
    title: "Producción",
    description: "Órdenes en fabricación",
    value: "248 unidades",
    detail: "92% de cumplimiento",
    status: "ready",
    icon: Factory,
    tone: "teal",
    progress: 92,
  },
  {
    id: "history",
    title: "Históricos",
    description: "Evolución de ingresos",
    value: "$ 42,6 M",
    detail: "Últimos 6 meses",
    status: "ready",
    icon: History,
    tone: "blue",
    bars: [42, 48, 56, 51, 72, 86],
  },
  {
    id: "patterns",
    title: "Patrones",
    description: "Hallazgos del negocio",
    value: "3 señales",
    detail: "Mayor demanda los viernes",
    status: "ready",
    icon: Sparkles,
    tone: "orange",
  },
  {
    id: "alerts",
    title: "Alertas",
    description: "Requieren atención",
    value: "5 pendientes",
    detail: "2 son de alta prioridad",
    status: "ready",
    icon: AlertTriangle,
    tone: "rose",
  },
]

export const widgetStatusLabels = {
  ready: "Actualizado hace 8 min",
  loading: "Sincronizando datos",
  empty: "Esperando configuración",
  error: "Actualización interrumpida",
}