'use client'

import { Activity, ArrowDown, ArrowRight, CheckCircle2, CircleHelp, Clock3, Database, FileCode2, GitBranch, LockKeyhole, Network, Server, ShieldCheck, Sparkles } from 'lucide-react'

const contractRows = [
  { method: 'GET', endpoint: '/api/v1/exports/preview', purpose: 'Consulta resumen y disponibilidad', status: '200 OK', color: '#62d89b' },
  { method: 'POST', endpoint: '/api/v1/exports', purpose: 'Solicita una exportación', status: '202 Accepted', color: '#55b9ee' },
  { method: 'GET', endpoint: '/api/v1/operations/:id', purpose: 'Consulta progreso y resultado', status: '200 OK', color: '#a998ff' },
]

const layers = [
  { icon: Network, label: 'Frontend', detail: 'Consume contratos HTTP', color: '#55b9ee' },
  { icon: Server, label: 'Express API', detail: 'Valida, autoriza y orquesta', color: '#ff8d94' },
  { icon: GitBranch, label: 'Servicios / ETL', detail: 'Procesa fuera de la interfaz', color: '#f2c45c' },
  { icon: Database, label: 'MySQL', detail: 'Persistencia detrás de servicios', color: '#62d89b' },
]

function Logo() {
  return <div className="flex items-center gap-2.5"><div className="grid size-8 place-items-center rounded-lg bg-[#f4511e] shadow-[0_0_18px_rgba(244,81,30,.28)]"><span className="text-lg text-white">✣</span></div><span className="text-[15px] font-bold tracking-tight text-[#f3f5f7]">Stockflow</span></div>
}

function SectionTitle({ eyebrow, title, children }) {
  return <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><p className="mb-1 text-[10px] font-semibold uppercase tracking-[.16em] text-[#ff792c]">{eyebrow}</p><h2 className="text-base font-semibold text-[#edf2f7]">{title}</h2></div>{children}</div>
}

export default function Page() {
  return <main className="min-h-screen bg-[#090d15] text-[#f3f5f7]"><header className="border-b border-[#202b39] bg-[#0a0f18]/95"><div className="mx-auto flex h-[66px] max-w-[1180px] items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm text-[#8792a4] md:flex"><a className="text-[#e8edf3]" href="#contratos">Contratos</a><a className="hover:text-white" href="#flujo">Flujo de datos</a><a className="hover:text-white" href="#operacion">Operación</a></nav><div className="flex items-center gap-4"><span className="hidden text-sm text-[#8f9bac] sm:block">Vista técnica</span><button aria-label="Abrir ayuda" className="grid size-8 place-items-center rounded-full border border-[#293546] text-[#8490a3]"><CircleHelp size={16} /></button><div className="grid size-8 place-items-center rounded-full bg-[#293546] text-xs font-semibold text-[#dbe2ea]">API</div></div></div></header>

<div className="mx-auto max-w-[1180px] px-5 py-8 lg:px-8 lg:py-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-medium uppercase tracking-[.18em] text-[#ff792c]">Arquitectura de integración</p><h1 className="text-2xl font-bold tracking-tight sm:text-[30px]">Contratos y operación de datos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8e9aac]">Esta interfaz es de consulta: consume únicamente contratos del backend y no ejecuta ETL ni accede directamente a MySQL.</p></div><div className="flex items-center gap-2 rounded-lg border border-[#24563c] bg-[#102b20] px-3 py-2"><ShieldCheck size={15} className="text-[#62d89b]" /><span className="text-xs text-[#a9d8ba]">Acceso por API autorizado</span></div></div>

<section id="flujo" className="mb-6 rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><SectionTitle eyebrow="Flujo visible" title="Frontend → Express → servicios/ETL → MySQL"><span className="flex items-center gap-1.5 text-xs text-[#62d89b]"><Activity size={14} />Canal operativo</span></SectionTitle><div className="grid gap-3 md:grid-cols-7 md:items-center">{layers.map(({ icon: Icon, label, detail, color }, index) => <div key={label} className="contents"><div className="rounded-lg border border-[#293749] bg-[#111a26] p-4 md:col-span-1"><span className="grid size-9 place-items-center rounded-lg" style={{ color, backgroundColor: `${color}18` }}><Icon size={17} /></span><p className="mt-3 text-sm font-semibold text-[#e5ebf1]">{label}</p><p className="mt-1 text-[11px] leading-4 text-[#7f8da0]">{detail}</p></div>{index < layers.length - 1 && <div className="flex justify-center text-[#526073] md:col-span-1"><ArrowRight className="hidden md:block" size={18} /><ArrowDown className="md:hidden" size={18} /></div>}</div>)}</div><div className="mt-4 flex items-start gap-2 rounded-lg border border-[#5b4320] bg-[#251d12] p-3 text-xs text-[#e7c873]"><LockKeyhole size={15} className="mt-0.5 shrink-0" /><p><strong className="font-semibold">Límite de responsabilidad:</strong> la UI no contiene credenciales, consultas SQL, jobs ni lógica ETL. Solo envía solicitudes al API y presenta el estado devuelto.</p></div></section>

<div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section id="contratos" className="rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><SectionTitle eyebrow="01 · API pública" title="Contratos consumidos"><span className="rounded-full border border-[#334154] bg-[#111a26] px-2.5 py-1 text-[10px] text-[#9eabb9]">OpenAPI v1</span></SectionTitle><div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left"><thead><tr className="border-b border-[#293749] text-[10px] uppercase tracking-[.12em] text-[#718096]"><th className="pb-3 pr-4 font-medium">Método</th><th className="pb-3 pr-4 font-medium">Endpoint</th><th className="pb-3 pr-4 font-medium">Responsabilidad</th><th className="pb-3 font-medium">Respuesta</th></tr></thead><tbody>{contractRows.map((row) => <tr key={row.endpoint} className="border-b border-[#202b39] last:border-0"><td className="py-4 pr-4"><span className="rounded bg-[#163247] px-2 py-1 font-mono text-[10px] font-semibold text-[#70caff]">{row.method}</span></td><td className="py-4 pr-4 font-mono text-xs text-[#dce4ec]">{row.endpoint}</td><td className="py-4 pr-4 text-xs text-[#8997a8]">{row.purpose}</td><td className="py-4 text-xs font-medium" style={{ color: row.color }}>{row.status}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center gap-2 text-[11px] text-[#77869a]"><FileCode2 size={14} className="text-[#a998ff]" />Los esquemas de request, response y errores son responsabilidad del contrato Express.</div></section>

<aside id="operacion" className="space-y-6"><section className="rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><SectionTitle eyebrow="02 · Estado" title="Operación activa" /><div className="flex items-start gap-3 rounded-lg border border-[#284b62] bg-[#102b3a]/70 p-3"><span className="mt-0.5 grid size-8 place-items-center rounded-full bg-[#193e54] text-[#55b9ee]"><Clock3 size={16} /></span><div><p className="text-sm font-semibold text-[#dceefa]">Procesamiento en curso</p><p className="mt-1 text-[11px] leading-4 text-[#83a9bf]">El progreso proviene de GET /api/v1/operations/:id.</p></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#1b4053]"><div className="h-full w-[68%] rounded-full bg-[#55b9ee]" /></div><div className="mt-2 flex justify-between text-[10px] text-[#7892a5]"><span>operation_id: exp_2025_0618</span><span>68%</span></div></section><section className="rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><SectionTitle eyebrow="03 · Resultado" title="Respuesta del servicio" /><div className="rounded-lg border border-[#24563c] bg-[#102b20]/70 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#d9f7e7]"><CheckCircle2 size={17} className="text-[#62d89b]" />Contrato disponible</div><p className="mt-2 text-[11px] leading-5 text-[#9ec8b1]">La UI recibe el estado, metadatos y enlace de resultado desde Express. No interpreta ni reconstruye datos de MySQL.</p></div></section></aside></div>

<section className="mt-6 rounded-xl border border-[#293749] bg-[#0f1621] p-5 sm:p-6"><SectionTitle eyebrow="Observabilidad" title="Qué ocurre detrás del contrato"><span className="text-xs text-[#78879a]">Solo lectura</span></SectionTitle><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-[#293749] bg-[#111a26] p-4"><Sparkles size={16} className="text-[#a998ff]" /><p className="mt-3 text-sm font-medium text-[#e5ebf1]">Validación en Express</p><p className="mt-1 text-[11px] leading-4 text-[#7f8da0]">Autenticación, permisos, payload y errores normalizados antes de derivar la operación.</p></div><div className="rounded-lg border border-[#293749] bg-[#111a26] p-4"><GitBranch size={16} className="text-[#f2c45c" /><p className="mt-3 text-sm font-medium text-[#e5ebf1]">Orquestación de servicios</p><p className="mt-1 text-[11px] leading-4 text-[#7f8da0]">Los servicios y ETL ejecutan trabajos fuera del navegador y actualizan el estado de operación.</p></div><div className="rounded-lg border border-[#293749] bg-[#111a26] p-4"><Database size={16} className="text-[#62d89b" /><p className="mt-3 text-sm font-medium text-[#e5ebf1]">Persistencia aislada</p><p className="mt-1 text-[11px] leading-4 text-[#7f8da0]">MySQL solo es accesible desde la capa de servicios autorizada, nunca desde este frontend.</p></div></div></section></div></main>
}
